# Generated by Django 2.2.24 on 2021-11-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200414_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartner',
            name='edx_oauth2_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Open EDX Oauth2 Key'),
        ),
        migrations.AddField(
            model_name='historicalpartner',
            name='edx_oauth2_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Open EDX Oauth2 Password'),
        ),
        migrations.AddField(
            model_name='historicalpartner',
            name='edx_oauth2_provider_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Open EDX Oauth2 Provider URL'),
        ),
        migrations.AddField(
            model_name='partner',
            name='edx_oauth2_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Open EDX Oauth2 Key'),
        ),
        migrations.AddField(
            model_name='partner',
            name='edx_oauth2_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Open EDX Oauth2 Password'),
        ),
        migrations.AddField(
            model_name='partner',
            name='edx_oauth2_provider_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Open EDX Oauth2 Provider URL'),
        ),
    ]
