# Generated by Django 3.2.8 on 2021-11-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartner',
            name='edx_oauth2_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Open EDX Oauth2 Key'),
        ),
        migrations.AddField(
            model_name='historicalpartner',
            name='edx_oauth2_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Open EDX Oauth2 Password'),
        ),
        migrations.AddField(
            model_name='historicalpartner',
            name='edx_oauth2_provider_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Open EDX Oauth2 Provider URL'),
        ),
        migrations.AddField(
            model_name='partner',
            name='edx_oauth2_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Open EDX Oauth2 Key'),
        ),
        migrations.AddField(
            model_name='partner',
            name='edx_oauth2_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Open EDX Oauth2 Password'),
        ),
        migrations.AddField(
            model_name='partner',
            name='edx_oauth2_provider_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Open EDX Oauth2 Provider URL'),
        ),
    ]
